function createfigure(X1, YMatrix1)
%CREATEFIGURE(X1, YMATRIX1)
%  X1:  vector of x data
%  YMATRIX1:  matrix of y data

%  Auto-generated by MATLAB on 08-Apr-2017 20:59:00

% Create figure
figure;

% Create axes
axes1 = axes('Position',[0.3328125 0.11 0.374999999999999 0.815]);
hold(axes1,'on');

% Create multiple lines using matrix input to plot
plot1 = plot(X1,YMatrix1,'LineWidth',1);
set(plot1(1),'DisplayName','GLCM',...
    'MarkerFaceColor',[0.600000023841858 0.200000002980232 0],...
    'Marker','square',...
    'Color',[0.600000023841858 0.200000002980232 0]);
set(plot1(2),'DisplayName','CCV','MarkerFaceColor',[1 0 0],'Marker','v',...
    'Color',[1 0 0]);
set(plot1(3),'DisplayName','LTP','MarkerFaceColor',[0 0 1],'Marker','o',...
    'Color',[0 0 1]);
set(plot1(4),'DisplayName','GLCM+CCV','MarkerFaceColor',[1 0 1],...
    'Marker','^',...
    'Color',[1 0 1]);
set(plot1(5),'DisplayName','GLCM+LTP','MarkerFaceColor',[0 0 0],...
    'Marker','pentagram',...
    'Color',[0 0 0]);
set(plot1(6),'DisplayName','CCV+LTP','MarkerFaceColor',[0 1 1],...
    'Marker','diamond',...
    'Color',[0 1 1]);
set(plot1(7),'DisplayName','GLCM+CCV+LTP',...
    'MarkerFaceColor',[0.164705887436867 0.384313732385635 0.274509817361832],...
    'Marker','hexagram',...
    'Color',[0.164705887436867 0.384313732385635 0.274509817361832]);

% Create xlabel
xlabel('No. of training images per class');

% Create ylabel
ylabel('Average Accuracy (%)');

box(axes1,'on');
% Create legend
legend1 = legend(axes1,'show');
set(legend1,'Location','best');

